// <auto-generated />
using System;
using EU_Work.Pages.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EU_Work.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EU_Work.Pages.Models.EducationInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Faculty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkFormid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("WorkFormid");

                    b.ToTable("EducationInfo");
                });

            modelBuilder.Entity("EU_Work.Pages.Models.TaksForm", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("officilal_eu_work_any_time")
                        .HasColumnType("bit");

                    b.Property<bool>("officilal_eu_work_now")
                        .HasColumnType("bit");

                    b.Property<bool>("officilal_ukr_work_any_time")
                        .HasColumnType("bit");

                    b.Property<bool>("officilal_ukr_work_now")
                        .HasColumnType("bit");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("presonal_data_agree")
                        .HasColumnType("bit");

                    b.Property<string>("sname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TaksForms");
                });

            modelBuilder.Entity("EU_Work.Pages.Models.WorkForm", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("about")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addres_official")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("officilal_eu_work_any_time")
                        .HasColumnType("bit");

                    b.Property<bool>("officilal_eu_work_now")
                        .HasColumnType("bit");

                    b.Property<bool>("officilal_ukr_work_any_time")
                        .HasColumnType("bit");

                    b.Property<bool>("officilal_ukr_work_now")
                        .HasColumnType("bit");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("presonal_data_agree")
                        .HasColumnType("bit");

                    b.Property<string>("sname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("WorkForms");
                });

            modelBuilder.Entity("EU_Work.Pages.Models.WorkInfo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AvrSalery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OffenThinks")
                        .HasColumnType("bit");

                    b.Property<string>("Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaksFormid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("TaksFormid");

                    b.ToTable("WorkInfo");
                });

            modelBuilder.Entity("EU_Work.Pages.Models.EducationInfo", b =>
                {
                    b.HasOne("EU_Work.Pages.Models.WorkForm", null)
                        .WithMany("educations")
                        .HasForeignKey("WorkFormid");
                });

            modelBuilder.Entity("EU_Work.Pages.Models.WorkInfo", b =>
                {
                    b.HasOne("EU_Work.Pages.Models.TaksForm", null)
                        .WithMany("Works")
                        .HasForeignKey("TaksFormid");
                });
#pragma warning restore 612, 618
        }
    }
}
